#端口号配置
server:
  port: 8088
spring:
  #jdbc配置
  datasource:
    url: jdbc:oracle:thin:@192.168.90.103:1521:hkhszq
    username: hsdc_ro
    password: hsdc0011
    driver-class-name: oracle.jdbc.driver.OracleDriver
#mybatis配置
mybatis:
  #映射文件路径
  mapper-locations: classpath:mapper/*.xml


